version: "3.7"

services:
  web:
    entrypoint: /entrypoint.sh
    build: ./
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./droids_demand_api/settings/dev.py
