# Generated by Django 3.1.4 on 2020-12-10 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_column='uf', max_length=2, unique=True, verbose_name='Uf')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'db_table': 'uf',
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Anunciante')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'db_table': 'demand',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Contato')),
                ('demand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demand.demand')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'demand_contact',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demand.uf', verbose_name='Uf')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=9, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('sector', models.CharField(blank=True, max_length=200, verbose_name='Bairro')),
                ('zipcode', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demand.city', verbose_name='Cidade')),
                ('demand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demand.demand')),
                ('uf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demand.uf', verbose_name='Uf')),
            ],
            options={
                'verbose_name': 'Endereço de entrega',
                'verbose_name_plural': 'Endereços de entrega',
                'db_table': 'demand_address',
                'ordering': ['-id'],
            },
        ),
    ]
